"""Initial schema

Revision ID: c13cb2e4d0f3
Revises: e71d11ae3cda
Create Date: 2023-09-07 19:48:19.914094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13cb2e4d0f3'
down_revision: Union[str, None] = 'e71d11ae3cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
